<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * CalendarEvent
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * CalendarEvent
 * @description A calendar event returned from the API
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class CalendarEvent
{
    /**
    *
    * 
    * @param string $id
    *
    * 
    * @param string $instance
    *
    * 
    * @param string $source
    *
    * 
    * @param string $createdTimestamp
    *
    * 
    * @param string $updatedTimestamp
    *
    * 
    * @param null | string $externalUid
    *
    * 
    * @param null | string $title
    *
    * 
    * @param null | string $description
    *
    * 
    * @param string $startTimestamp
    *
    * 
    * @param string $endTimestamp
    *
    * 
    * @param null | string $organiser
    *
    * 
    * @param null | string $attendee
    *
    * 
    * @param null | string $status
    *
    * 
    * @param null | string $location
    *
    * 
    * @param null | string $type
    *
    * 
    * @param null | string $tags
    *
    * 
    * @param null | string $trigger
    *
    * 
    * @param null | string $action
    *
    * 
    * @param null | string $reminderDescription
    *
    * 
    * @param null | string $contextName
    */

    public function __construct(
        public string $id,
        public string $instance,
        public string $source,
        public string $createdTimestamp,
        public string $updatedTimestamp,
        public string $startTimestamp,
        public string $endTimestamp,
        public ?string $externalUid = null,
        public ?string $title = null,
        public ?string $description = null,
        public ?string $organiser = null,
        public ?string $attendee = null,
        public ?string $status = null,
        public ?string $location = null,
        public ?string $type = null,
        public ?string $tags = null,
        public ?string $trigger = null,
        public ?string $action = null,
        public ?string $reminderDescription = null,
        public ?string $contextName = null,
    ) {}
}

