<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * CalendarEventCreateRequestBody
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * CalendarEventCreateRequestBody
 * @description Fields for creating a generic calendar event
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class CalendarEventCreateRequestBody
{
    /**
    *
    * Title of the event
    * @param string $title
    *
    * Detailed description of the event
    * @param string $description
    *
    * Start date and time as Unix timestamp
    * @param int $startTimestamp
    *
    * End date and time as Unix timestamp
    * @param int $endTimestamp
    *
    * 
    * @param \Mydex\ApiPdxSdk\Laravel\Model\CalendarEventCommonRequestBodyFieldsStatus $status
    *
    * Creator of the event
    * @param string $organiser
    *
    * Person attending the event
    * @param string $attendee
    *
    * Event location
    * @param string $location
    *
    * 
    * @param null | \Mydex\ApiPdxSdk\Laravel\Model\CalendarEventCreateRequestBodyAllOfType $type
    */

    public function __construct(
        public string $title,
        public string $description,
        public int $startTimestamp,
        public int $endTimestamp,
        public \Mydex\ApiPdxSdk\Laravel\Model\CalendarEventCommonRequestBodyFieldsStatus $status,
        public string $organiser,
        public string $attendee,
        public string $location,
        public ?\Mydex\ApiPdxSdk\Laravel\Model\CalendarEventCreateRequestBodyAllOfType $type = null,
    ) {}
}

