<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * CalendarAppointmentCreateRequestBodyAllOfContext
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * CalendarAppointmentCreateRequestBodyAllOfContext
 * @description The context the appointment belongs to e.g. a referral
 */
enum CalendarAppointmentCreateRequestBodyAllOfContext: string
{
        case REFERRAL = 'referral';
        case UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';
}
