<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * ReferralCommonRequestBodyFields
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * ReferralCommonRequestBodyFields
 * @description Common fields shared across all referral types
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class ReferralCommonRequestBodyFields
{
    /**
    *
    * ID of the service being referred to
    * @param int $serviceId
    *
    * Background information about the referree
    * @param string $referreeBackground
    *
    * Requirements of the referree
    * @param string $referreeRequirements
    *
    * 
    * @param \Mydex\ApiPdxSdk\Laravel\Model\ReferralCommonRequestBodyFieldsReferreeAvailability $referreeAvailability
    *
    * Name of the person making the referral
    * @param string $referrerName
    *
    * Name of the service
    * @param string $serviceName
    *
    * Description of the service
    * @param string $serviceDescription
    *
    * URL of the service
    * @param string $serviceUrl
    *
    * Email address of the service
    * @param string $serviceEmail
    *
    * Contact number for the service
    * @param string $contactNumber
    *
    * Internal memo or notes
    * @param string $memo
    *
    * Start time as a Unix timestamp
    * @param int $startTime
    */

    public function __construct(
        public int $serviceId,
        public string $referreeBackground,
        public string $referreeRequirements,
        public \Mydex\ApiPdxSdk\Laravel\Model\ReferralCommonRequestBodyFieldsReferreeAvailability $referreeAvailability,
        public string $referrerName,
        public string $serviceName,
        public string $serviceDescription,
        public string $serviceUrl,
        public string $serviceEmail,
        public string $contactNumber,
        public string $memo,
        public int $startTime,
    ) {}
}

