<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * ReferralSingleResponseReferral
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * ReferralSingleResponseReferral
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class ReferralSingleResponseReferral
{
    /**
    *
    * 
    * @param int $id
    *
    * 
    * @param int $createdTimestamp
    *
    * 
    * @param int $serviceId
    *
    * 
    * @param string $type
    *
    * 
    * @param \Mydex\ApiPdxSdk\Laravel\Model\ReferralStatusUpdateRequestBodyStatus $status
    *
    * 
    * @param string $memo
    */

    public function __construct(
        public int $id,
        public int $createdTimestamp,
        public int $serviceId,
        public string $type,
        public \Mydex\ApiPdxSdk\Laravel\Model\ReferralStatusUpdateRequestBodyStatus $status,
        public string $memo,
    ) {}
}

