<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * SecureMessageCommonFields
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * SecureMessageCommonFields
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class SecureMessageCommonFields
{
    /**
    *
    * Content of the message
    * @param string $messageContent
    *
    * ID of the conversation formatted like {context}-{context_id} where context is e.g. &#39;referral&#39; and context_id is the id of the specifc record in that context.
    * @param string $conversationId
    */

    public function __construct(
        public string $messageContent,
        public string $conversationId,
    ) {}
}

