<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * SecureMessage
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * SecureMessage
 * @description A single message within a conversation
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class SecureMessage
{
    /**
    *
    * Message ID
    * @param string $id
    *
    * Conversation identifier
    * @param string $conversationId
    *
    * Recipient of the message (present on sent messages)
    * @param string $messageTo
    *
    * Sender of the message (present on received messages)
    * @param string $messageFrom
    *
    * Timestamp when message was sent
    * @param string $timeSent
    *
    * Timestamp when message was received
    * @param string $timeReceived
    *
    * Content of the message
    * @param string $messageContent
    *
    * 
    * @param \Mydex\ApiPdxSdk\Laravel\Model\SecureMessageStatus $status
    */

    public function __construct(
        public string $id,
        public string $conversationId,
        public string $messageTo,
        public string $messageFrom,
        public string $timeSent,
        public string $timeReceived,
        public string $messageContent,
        public \Mydex\ApiPdxSdk\Laravel\Model\SecureMessageStatus $status,
    ) {}
}

