<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * TimelineItemReferral
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * TimelineItemReferral
 * @description A single timeline item representing a referral
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class TimelineItemReferral
{
    /**
    *
    * Type of feature block this timeline item belongs to
    * @param string $featureBlock
    *
    * ID of the feature block record i.e. the referral id
    * @param int $featureBlockId
    *
    * 
    * @param string $instance
    *
    * The context within which this record was created i.e. the specific connection
    * @param string $source
    *
    * 
    * @param int $createdTimestamp
    *
    * 
    * @param int $updatedTimestamp
    *
    * The id of the service that the referral relates to
    * @param int $serviceId
    *
    * 
    * @param string $serviceName
    *
    * 
    * @param string $serviceDescription
    *
    * 
    * @param string $serviceUrl
    *
    * 
    * @param string $serviceEmail
    *
    * 
    * @param string $contactName
    *
    * 
    * @param string $contactTitle
    *
    * 
    * @param string $contactNumber
    *
    * 
    * @param string $referrerName
    *
    * 
    * @param \Mydex\ApiPdxSdk\Laravel\Model\ReferralStatusUpdateRequestBodyStatus $status
    *
    * 
    * @param string $externalId
    *
    * 
    * @param int $startTime
    *
    * 
    * @param int $endTime
    *
    * 
    * @param bool $isProcessed
    *
    * 
    * @param int $completeTime
    *
    * 
    * @param string $memo
    *
    * 
    * @param string $duration
    *
    * 
    * @param string $referreeBackground
    *
    * 
    * @param string $referreeRequirements
    *
    * Availability of the referree in AM/PM slots
    * @param object $referreeAvailability
    *
    * 
    * @param string $type
    *
    * 
    * @param string $startTimestamp
    */

    public function __construct(
        public string $featureBlock,
        public int $featureBlockId,
        public string $instance,
        public string $source,
        public int $createdTimestamp,
        public int $updatedTimestamp,
        public int $serviceId,
        public string $serviceName,
        public string $serviceDescription,
        public string $serviceUrl,
        public string $serviceEmail,
        public string $contactName,
        public string $contactTitle,
        public string $contactNumber,
        public string $referrerName,
        public \Mydex\ApiPdxSdk\Laravel\Model\ReferralStatusUpdateRequestBodyStatus $status,
        public string $externalId,
        public int $startTime,
        public int $endTime,
        public bool $isProcessed,
        public int $completeTime,
        public string $memo,
        public string $duration,
        public string $referreeBackground,
        public string $referreeRequirements,
        public object $referreeAvailability,
        public string $type,
        public string $startTimestamp,
    ) {}
}

