<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * TimelineResponseTimelineInner
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * TimelineResponseTimelineInner
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class TimelineResponseTimelineInner
{
    /**
    *
    * 
    * @param int $id
    *
    * 
    * @param string $featureBlock
    *
    * 
    * @param string $featureBlockId
    *
    * 
    * @param string $startTimestamp
    *
    * 
    * @param int $itemTimestamp
    *
    * 
    * @param string $serviceDescription
    *
    * 
    * @param string $serviceName
    *
    * 
    * @param string $contactName
    *
    * 
    * @param string $contactTitle
    *
    * 
    * @param string $memo
    *
    * 
    * @param string $status
    *
    * 
    * @param int $createdTimestamp
    *
    * 
    * @param string $messageFrom
    *
    * 
    * @param string $messageTo
    *
    * 
    * @param string $messageContent
    *
    * 
    * @param string $endTimestamp
    *
    * 
    * @param string $title
    *
    * 
    * @param string $location
    *
    * 
    * @param string $organiser
    *
    * 
    * @param string $description
    *
    * 
    * @param string $durationString
    *
    * 
    * @param float $durationOfEvent
    */

    public function __construct(
        public int $id,
        public string $featureBlock,
        public string $featureBlockId,
        public string $startTimestamp,
        public int $itemTimestamp,
        public string $serviceDescription,
        public string $serviceName,
        public string $contactName,
        public string $contactTitle,
        public string $memo,
        public string $status,
        public int $createdTimestamp,
        public string $messageFrom,
        public string $messageTo,
        public string $messageContent,
        public string $endTimestamp,
        public string $title,
        public string $location,
        public string $organiser,
        public string $description,
        public string $durationString,
        public float $durationOfEvent,
    ) {}
}

