<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * TimelineResponse
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * TimelineResponse
 * @description Response containing a mixed timeline of calendar events, referrals, and secure messages
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class TimelineResponse
{
    /**
    *
    * 
    * @param int $success
    *
    * Array of timeline items, which can be calendar events, referrals, or secure messages
    * @param \Mydex\ApiPdxSdk\Laravel\Model\TimelineResponseTimelineInner[] $timeline
    */

    public function __construct(
        public int $success,
        public array $timeline,
    ) {}
}

