<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * TimelineSingleItemResponseTimelineItem
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * TimelineSingleItemResponseTimelineItem
 * @description The timeline item, which can be one of multiple types, returned as an object
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class TimelineSingleItemResponseTimelineItem
{
    /**
    *
    * Type of feature block this timeline item belongs to
    * @param string $featureBlock
    *
    * ID of the feature block
    * @param int $featureBlockId
    *
    * 
    * @param string $instance
    *
    * 
    * @param string $source
    *
    * 
    * @param string $createdTimestamp
    *
    * 
    * @param string $updatedTimestamp
    *
    * The id of the service that the referral relates to
    * @param int $serviceId
    *
    * 
    * @param string $serviceName
    *
    * 
    * @param string $serviceDescription
    *
    * 
    * @param string $serviceUrl
    *
    * 
    * @param string $serviceEmail
    *
    * 
    * @param string $contactName
    *
    * 
    * @param string $contactTitle
    *
    * 
    * @param string $contactNumber
    *
    * 
    * @param string $referrerName
    *
    * 
    * @param null | string $status
    *
    * 
    * @param string $externalId
    *
    * 
    * @param int $startTime
    *
    * 
    * @param int $endTime
    *
    * 
    * @param bool $isProcessed
    *
    * 
    * @param int $completeTime
    *
    * 
    * @param string $memo
    *
    * 
    * @param string $duration
    *
    * 
    * @param string $referreeBackground
    *
    * 
    * @param string $referreeRequirements
    *
    * Availability of the referree in AM/PM slots
    * @param object $referreeAvailability
    *
    * 
    * @param null | string $type
    *
    * 
    * @param string $startTimestamp
    *
    * Raw timestamp of the timeline item
    * @param int $itemTimestamp
    *
    * Conversation identifier
    * @param string $conversationId
    *
    * Timestamp when message was sent
    * @param string $timeSent
    *
    * Timestamp when message was received
    * @param string $timeReceived
    *
    * Sender of the message (present on received messages)
    * @param string $messageFrom
    *
    * Recipient of the message (present on sent messages)
    * @param string $messageTo
    *
    * Content of the message
    * @param string $messageContent
    *
    * 
    * @param null | string $externalUid
    *
    * 
    * @param null | string $title
    *
    * 
    * @param null | string $description
    *
    * 
    * @param string $endTimestamp
    *
    * 
    * @param null | string $organiser
    *
    * 
    * @param null | string $attendee
    *
    * 
    * @param null | string $location
    *
    * 
    * @param null | string $tags
    *
    * 
    * @param null | string $trigger
    *
    * 
    * @param null | string $action
    *
    * 
    * @param null | string $reminderDescription
    *
    * 
    * @param string $durationString
    *
    * 
    * @param float $durationOfEvent
    */

    public function __construct(
        public string $featureBlock,
        public int $featureBlockId,
        public string $instance,
        public string $source,
        public string $createdTimestamp,
        public string $updatedTimestamp,
        public int $serviceId,
        public string $serviceName,
        public string $serviceDescription,
        public string $serviceUrl,
        public string $serviceEmail,
        public string $contactName,
        public string $contactTitle,
        public string $contactNumber,
        public string $referrerName,
        public string $externalId,
        public int $startTime,
        public int $endTime,
        public bool $isProcessed,
        public int $completeTime,
        public string $memo,
        public string $duration,
        public string $referreeBackground,
        public string $referreeRequirements,
        public object $referreeAvailability,
        public string $startTimestamp,
        public int $itemTimestamp,
        public string $conversationId,
        public string $timeSent,
        public string $timeReceived,
        public string $messageFrom,
        public string $messageTo,
        public string $messageContent,
        public string $endTimestamp,
        public string $durationString,
        public float $durationOfEvent,
        public ?string $status = null,
        public ?string $type = null,
        public ?string $externalUid = null,
        public ?string $title = null,
        public ?string $description = null,
        public ?string $organiser = null,
        public ?string $attendee = null,
        public ?string $location = null,
        public ?string $tags = null,
        public ?string $trigger = null,
        public ?string $action = null,
        public ?string $reminderDescription = null,
    ) {}
}

