<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * TimelineItemSecureMessage
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * TimelineItemSecureMessage
 * @description A single timeline item representing a secure message
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class TimelineItemSecureMessage
{
    /**
    *
    * Type of feature block this timeline item belongs to
    * @param string $featureBlock
    *
    * ID of the feature block
    * @param int $featureBlockId
    *
    * Formatted start timestamp for display
    * @param string $startTimestamp
    *
    * Raw timestamp of the timeline item
    * @param int $itemTimestamp
    *
    * 
    * @param int $createdTimestamp
    *
    * 
    * @param int $updatedTimestamp
    *
    * Conversation identifier
    * @param string $conversationId
    *
    * Timestamp when message was sent
    * @param string $timeSent
    *
    * Timestamp when message was received
    * @param string $timeReceived
    *
    * Sender of the message (present on received messages)
    * @param string $messageFrom
    *
    * Recipient of the message (present on sent messages)
    * @param string $messageTo
    *
    * Content of the message
    * @param string $messageContent
    */

    public function __construct(
        public string $featureBlock,
        public int $featureBlockId,
        public string $startTimestamp,
        public int $itemTimestamp,
        public int $createdTimestamp,
        public int $updatedTimestamp,
        public string $conversationId,
        public string $timeSent,
        public string $timeReceived,
        public string $messageFrom,
        public string $messageTo,
        public string $messageContent,
    ) {}
}

