<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * TimelineResponseTimelineInnerOneOf1
 */
namespace Mydex\ApiPdxSdk\Laravel\Model;

/**
 * TimelineResponseTimelineInnerOneOf1
 * @description Secure message item
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class TimelineResponseTimelineInnerOneOf1
{
    /**
    *
    * 
    * @param int $id
    *
    * 
    * @param string $featureBlock
    *
    * 
    * @param string $featureBlockId
    *
    * 
    * @param string $startTimestamp
    *
    * 
    * @param int $itemTimestamp
    *
    * 
    * @param int $createdTimestamp
    *
    * 
    * @param string $messageFrom
    *
    * 
    * @param string $messageTo
    *
    * 
    * @param string $messageContent
    */

    public function __construct(
        public int $id,
        public string $featureBlock,
        public string $featureBlockId,
        public string $startTimestamp,
        public int $itemTimestamp,
        public int $createdTimestamp,
        public string $messageFrom,
        public string $messageTo,
        public string $messageContent,
    ) {}
}

