<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


use Illuminate\Support\Facades\Route;

/**
 * DELETE deleteCalendarEvent
 * Summary: Supports deleting a calendar-event.
 * Notes: Deletes an event in the user&#39;s calendar.
 */
Route::DELETE('/calendar/delete-event', [\OpenAPI\Server\Http\Controllers\CalendarController::class, 'deleteCalendarEvent'])->name('calendar.delete.calendar.event');

/**
 * GET getCalendarAppointments
 * Summary: Retrieve appointments for a given context
 * Notes: Returns a list of appointments filtered by context and context_id.
 */
Route::GET('/calendar/get-appointments', [\OpenAPI\Server\Http\Controllers\CalendarController::class, 'getCalendarAppointments'])->name('calendar.get.calendar.appointments');

/**
 * GET getCalendarEvents
 * Summary: Retrieve calendar events
 * Notes: Returns a list of calendar events.
 */
Route::GET('/calendar/get-events', [\OpenAPI\Server\Http\Controllers\CalendarController::class, 'getCalendarEvents'])->name('calendar.get.calendar.events');

/**
 * POST postCalendarAppointment
 * Summary: Supports adding a calendar-appointment.
 * Notes: Creates a new appointment in the user&#39;s calendar. An appointment must be made within a specified context e.g. a &#39;Referral&#39;
 */
Route::POST('/calendar/add-appointment', [\OpenAPI\Server\Http\Controllers\CalendarController::class, 'postCalendarAppointment'])->name('calendar.post.calendar.appointment');

/**
 * POST postCalendarEvent
 * Summary: Supports adding a calendar-event.
 * Notes: Creates a new event in the user&#39;s calendar.
 */
Route::POST('/calendar/add-event', [\OpenAPI\Server\Http\Controllers\CalendarController::class, 'postCalendarEvent'])->name('calendar.post.calendar.event');

/**
 * PUT putCalendarEvent
 * Summary: Supports updating a calendar-event.
 * Notes: Updates an event in the user&#39;s calendar. For example, updating the &#39;status&#39; from &#39;INVITED&#39; to &#39;CONFIRMED&#39; when a user accepts the invitation to an appointment.
 */
Route::PUT('/calendar/update-event', [\OpenAPI\Server\Http\Controllers\CalendarController::class, 'putCalendarEvent'])->name('calendar.put.calendar.event');

/**
 * GET getAllReferrals
 * Summary: Retrieve rall referrals for a given member.
 * Notes: Returns a list of referrals.
 */
Route::GET('/referrals/read-all', [\OpenAPI\Server\Http\Controllers\ReferralsController::class, 'getAllReferrals'])->name('referrals.get.all.referrals');

/**
 * GET getSingleReferral
 * Summary: Retrieve a single referral by id for a given member.
 * Notes: Returns the requested referral.
 */
Route::GET('/referrals/read-single', [\OpenAPI\Server\Http\Controllers\ReferralsController::class, 'getSingleReferral'])->name('referrals.get.single.referral');

/**
 * POST postSelfReferral
 * Summary: Supports self-referral.
 * Notes: Creates a new referral of type &#39;Self Referred&#39; in the member&#39;s PDS.
 */
Route::POST('/referrals/self-refer', [\OpenAPI\Server\Http\Controllers\ReferralsController::class, 'postSelfReferral'])->name('referrals.post.self.referral');

/**
 * PUT updateReferralStatus
 * Summary: Supports updating the status of a referral.
 * Notes: Updates the status of a member&#39;s referral specified by id. For example, having been referred to a service, the status is set by default to &#39;Referred&#39; and this route enables it to be updated to &#39;Accepted&#39; or &#39;Rejected&#39;
 */
Route::PUT('/referrals/update-status', [\OpenAPI\Server\Http\Controllers\ReferralsController::class, 'updateReferralStatus'])->name('referrals.update.referral.status');

/**
 * GET getSecureMessageConversation
 * Summary: Retrieve all secure messages for a given conversation.
 * Notes: Returns a list of secure messages that form part of a conversation.
 */
Route::GET('/secure-messages/conversation', [\OpenAPI\Server\Http\Controllers\SecureMessagesController::class, 'getSecureMessageConversation'])->name('secureMessages.get.secure.message.conversation');

/**
 * POST postSecureMessageReceive
 * Summary: Supports sending a message to the member&#39;s PDS.
 * Notes: Creates a new received message in the member&#39;s PDS.
 */
Route::POST('/secure-messages/receive', [\OpenAPI\Server\Http\Controllers\SecureMessagesController::class, 'postSecureMessageReceive'])->name('secureMessages.post.secure.message.receive');

/**
 * POST postSecureMessageSend
 * Summary: Supports sending a message from the member&#39;s PDS.
 * Notes: Creates a new sent message in the member&#39;s PDS.
 */
Route::POST('/secure-messages/send', [\OpenAPI\Server\Http\Controllers\SecureMessagesController::class, 'postSecureMessageSend'])->name('secureMessages.post.secure.message.send');

/**
 * GET getTimeline
 * Summary: Retrieve list of timeline items.
 * Notes: Returns a list of timeline items which includes: referrals, calendar events and secure messages.
 */
Route::GET('/timeline', [\OpenAPI\Server\Http\Controllers\TimelineController::class, 'getTimeline'])->name('timeline.get.timeline');

/**
 * GET getTimelineItem
 * Summary: Retrieve a single timeline item.
 * Notes: Returns a single timeline item based on feature block and feature block id requested e.g. a &#39;referral&#39; with id 123.
 */
Route::GET('/timeline/single-item', [\OpenAPI\Server\Http\Controllers\TimelineController::class, 'getTimelineItem'])->name('timeline.get.timeline.item');

