<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Http\Controllers;

use Crell\Serde\SerdeCommon;
use Illuminate\Routing\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


use Mydex\ApiPdxSdk\Laravel\Api\CalendarApiInterface;

class CalendarController extends Controller
{
    /**
     * Constructor
     */
    public function __construct(
        private readonly CalendarApiInterface $api,
        private readonly SerdeCommon $serde = new SerdeCommon(),
    )
    {
    }

    /**
     * Operation deleteCalendarEvent
     *
     * Supports deleting a calendar-event..
     *
     */
    public function deleteCalendarEvent(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();

        $calendarEventDeleteRequestBody = $this->serde->deserialize($request->getContent(), from: 'json', to: \Mydex\ApiPdxSdk\Laravel\Model\CalendarEventDeleteRequestBody::class);


        $apiResult = $this->api->deleteCalendarEvent($connectionToken, $uid, $conId, $calendarEventDeleteRequestBody);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\DeleteResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 400);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation getCalendarAppointments
     *
     * Retrieve appointments for a given context.
     *
     */
    public function getCalendarAppointments(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
                'connectionToken' => [
                    'required',
                    'string',
                ],
                'uid' => [
                    'required',
                    'string',
                ],
                'conId' => [
                    'required',
                    'string',
                ],
                'context' => [
                    'required',
                    'string',
                ],
                'contextId' => [
                    'required',
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();

        $context = $request->string('context')->value();

        $contextId = $request->integer('contextId');


        $apiResult = $this->api->getCalendarAppointments($connectionToken, $uid, $conId, $context, $contextId);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\GetAppointmentsResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 400);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation getCalendarEvents
     *
     * Retrieve calendar events.
     *
     */
    public function getCalendarEvents(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
                'connectionToken' => [
                    'required',
                    'string',
                ],
                'uid' => [
                    'required',
                    'string',
                ],
                'conId' => [
                    'required',
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();


        $apiResult = $this->api->getCalendarEvents($connectionToken, $uid, $conId);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\GetEventsResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation postCalendarAppointment
     *
     * Supports adding a calendar-appointment..
     *
     */
    public function postCalendarAppointment(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();

        $calendarAppointmentCreateRequestBody = $this->serde->deserialize($request->getContent(), from: 'json', to: \Mydex\ApiPdxSdk\Laravel\Model\CalendarAppointmentCreateRequestBody::class);


        $apiResult = $this->api->postCalendarAppointment($connectionToken, $uid, $conId, $calendarAppointmentCreateRequestBody);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 400);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation postCalendarEvent
     *
     * Supports adding a calendar-event..
     *
     */
    public function postCalendarEvent(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();

        $calendarEventCreateRequestBody = $this->serde->deserialize($request->getContent(), from: 'json', to: \Mydex\ApiPdxSdk\Laravel\Model\CalendarEventCreateRequestBody::class);


        $apiResult = $this->api->postCalendarEvent($connectionToken, $uid, $conId, $calendarEventCreateRequestBody);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 400);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation putCalendarEvent
     *
     * Supports updating a calendar-event..
     *
     */
    public function putCalendarEvent(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();

        $calendarEventUpdateRequestBody = $this->serde->deserialize($request->getContent(), from: 'json', to: \Mydex\ApiPdxSdk\Laravel\Model\CalendarEventUpdateRequestBody::class);


        $apiResult = $this->api->putCalendarEvent($connectionToken, $uid, $conId, $calendarEventUpdateRequestBody);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\UpdateResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 400);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
}
