<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Http\Controllers;

use Crell\Serde\SerdeCommon;
use Illuminate\Routing\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


use Mydex\ApiPdxSdk\Laravel\Api\ReferralsApiInterface;

class ReferralsController extends Controller
{
    /**
     * Constructor
     */
    public function __construct(
        private readonly ReferralsApiInterface $api,
        private readonly SerdeCommon $serde = new SerdeCommon(),
    )
    {
    }

    /**
     * Operation getAllReferrals
     *
     * Retrieve rall referrals for a given member..
     *
     */
    public function getAllReferrals(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
                'connectionToken' => [
                    'required',
                    'string',
                ],
                'uid' => [
                    'required',
                    'string',
                ],
                'conId' => [
                    'required',
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();


        $apiResult = $this->api->getAllReferrals($connectionToken, $uid, $conId);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\ReferralListResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation getSingleReferral
     *
     * Retrieve a single referral by id for a given member..
     *
     */
    public function getSingleReferral(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
                'connectionToken' => [
                    'required',
                    'string',
                ],
                'uid' => [
                    'required',
                    'string',
                ],
                'conId' => [
                    'required',
                    'string',
                ],
                'id' => [
                    'required',
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();

        $id = $request->string('id')->value();


        $apiResult = $this->api->getSingleReferral($connectionToken, $uid, $conId, $id);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\ReferralSingleResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation postSelfReferral
     *
     * Supports self-referral..
     *
     */
    public function postSelfReferral(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();

        $selfReferralRequestBody = $this->serde->deserialize($request->getContent(), from: 'json', to: \Mydex\ApiPdxSdk\Laravel\Model\SelfReferralRequestBody::class);


        $apiResult = $this->api->postSelfReferral($connectionToken, $uid, $conId, $selfReferralRequestBody);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 400);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation updateReferralStatus
     *
     * Supports updating the status of a referral..
     *
     */
    public function updateReferralStatus(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();

        $referralStatusUpdateRequestBody = $this->serde->deserialize($request->getContent(), from: 'json', to: \Mydex\ApiPdxSdk\Laravel\Model\ReferralStatusUpdateRequestBody::class);


        $apiResult = $this->api->updateReferralStatus($connectionToken, $uid, $conId, $referralStatusUpdateRequestBody);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\UpdateResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 400);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
}
