<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Http\Controllers;

use Crell\Serde\SerdeCommon;
use Illuminate\Routing\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


use Mydex\ApiPdxSdk\Laravel\Api\SecureMessagesApiInterface;

class SecureMessagesController extends Controller
{
    /**
     * Constructor
     */
    public function __construct(
        private readonly SecureMessagesApiInterface $api,
        private readonly SerdeCommon $serde = new SerdeCommon(),
    )
    {
    }

    /**
     * Operation getSecureMessageConversation
     *
     * Retrieve all secure messages for a given conversation..
     *
     */
    public function getSecureMessageConversation(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
                'connectionToken' => [
                    'required',
                    'string',
                ],
                'uid' => [
                    'required',
                    'string',
                ],
                'conId' => [
                    'required',
                    'string',
                ],
                'conversationId' => [
                    'required',
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();

        $conversationId = $request->string('conversationId')->value();


        $apiResult = $this->api->getSecureMessageConversation($connectionToken, $uid, $conId, $conversationId);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\SecureMessageConversationResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation postSecureMessageReceive
     *
     * Supports sending a message to the member's PDS..
     *
     */
    public function postSecureMessageReceive(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();

        $secureMessageReceiveRequest = $this->serde->deserialize($request->getContent(), from: 'json', to: \Mydex\ApiPdxSdk\Laravel\Model\SecureMessageReceiveRequest::class);


        $apiResult = $this->api->postSecureMessageReceive($connectionToken, $uid, $conId, $secureMessageReceiveRequest);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 400);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation postSecureMessageSend
     *
     * Supports sending a message from the member's PDS..
     *
     */
    public function postSecureMessageSend(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();

        $secureMessageSendRequest = $this->serde->deserialize($request->getContent(), from: 'json', to: \Mydex\ApiPdxSdk\Laravel\Model\SecureMessageSendRequest::class);


        $apiResult = $this->api->postSecureMessageSend($connectionToken, $uid, $conId, $secureMessageSendRequest);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 400);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
}
