<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Http\Controllers;

use Crell\Serde\SerdeCommon;
use Illuminate\Routing\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


use Mydex\ApiPdxSdk\Laravel\Api\TimelineApiInterface;

class TimelineController extends Controller
{
    /**
     * Constructor
     */
    public function __construct(
        private readonly TimelineApiInterface $api,
        private readonly SerdeCommon $serde = new SerdeCommon(),
    )
    {
    }

    /**
     * Operation getTimeline
     *
     * Retrieve list of timeline items..
     *
     */
    public function getTimeline(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
                'connectionToken' => [
                    'required',
                    'string',
                ],
                'uid' => [
                    'required',
                    'string',
                ],
                'conId' => [
                    'required',
                    'string',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();


        $apiResult = $this->api->getTimeline($connectionToken, $uid, $conId);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\TimelineResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation getTimelineItem
     *
     * Retrieve a single timeline item..
     *
     */
    public function getTimelineItem(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
                'connectionToken' => [
                    'required',
                    'string',
                ],
                'uid' => [
                    'required',
                    'string',
                ],
                'conId' => [
                    'required',
                    'string',
                ],
                'featureBlock' => [
                    'required',
                ],
                'featureBlockId' => [
                    'required',
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $connectionToken = $request->string('connectionToken')->value();

        $uid = $request->string('uid')->value();

        $conId = $request->string('conId')->value();

        $featureBlock = $this->serde->deserialize($request->getContent(), from: 'json', to: \Mydex\ApiPdxSdk\Laravel\Model\GetTimelineItemFeatureBlockParameter::class);

        $featureBlockId = $request->integer('featureBlockId');


        $apiResult = $this->api->getTimelineItem($connectionToken, $uid, $conId, $featureBlock, $featureBlockId);

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\TimelineSingleItemResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 401);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
}
