<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace Mydex\ApiPdxSdk\Laravel\Api;


interface CalendarApiInterface {


    /**
     * Operation deleteCalendarEvent
     *
     * Supports deleting a calendar-event.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @param null | \Mydex\ApiPdxSdk\Laravel\Model\CalendarEventDeleteRequestBody $calendarEventDeleteRequestBody
     * @return \Mydex\ApiPdxSdk\Laravel\Model\DeleteResponse | \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function deleteCalendarEvent(
            string $connectionToken,
            string $uid,
            string $conId,
            ?\Mydex\ApiPdxSdk\Laravel\Model\CalendarEventDeleteRequestBody $calendarEventDeleteRequestBody,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\DeleteResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;


    /**
     * Operation getCalendarAppointments
     *
     * Retrieve appointments for a given context
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @param string $context
     * @param int $contextId
     * @return \Mydex\ApiPdxSdk\Laravel\Model\GetAppointmentsResponse | \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function getCalendarAppointments(
            string $connectionToken,
            string $uid,
            string $conId,
            string $context,
            int $contextId,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\GetAppointmentsResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;


    /**
     * Operation getCalendarEvents
     *
     * Retrieve calendar events
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @return \Mydex\ApiPdxSdk\Laravel\Model\GetEventsResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function getCalendarEvents(
            string $connectionToken,
            string $uid,
            string $conId,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\GetEventsResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;


    /**
     * Operation postCalendarAppointment
     *
     * Supports adding a calendar-appointment.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @param null | \Mydex\ApiPdxSdk\Laravel\Model\CalendarAppointmentCreateRequestBody $calendarAppointmentCreateRequestBody
     * @return \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse | \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function postCalendarAppointment(
            string $connectionToken,
            string $uid,
            string $conId,
            ?\Mydex\ApiPdxSdk\Laravel\Model\CalendarAppointmentCreateRequestBody $calendarAppointmentCreateRequestBody,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;


    /**
     * Operation postCalendarEvent
     *
     * Supports adding a calendar-event.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @param null | \Mydex\ApiPdxSdk\Laravel\Model\CalendarEventCreateRequestBody $calendarEventCreateRequestBody
     * @return \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse | \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function postCalendarEvent(
            string $connectionToken,
            string $uid,
            string $conId,
            ?\Mydex\ApiPdxSdk\Laravel\Model\CalendarEventCreateRequestBody $calendarEventCreateRequestBody,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;


    /**
     * Operation putCalendarEvent
     *
     * Supports updating a calendar-event.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @param null | \Mydex\ApiPdxSdk\Laravel\Model\CalendarEventUpdateRequestBody $calendarEventUpdateRequestBody
     * @return \Mydex\ApiPdxSdk\Laravel\Model\UpdateResponse | \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function putCalendarEvent(
            string $connectionToken,
            string $uid,
            string $conId,
            ?\Mydex\ApiPdxSdk\Laravel\Model\CalendarEventUpdateRequestBody $calendarEventUpdateRequestBody,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\UpdateResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;

}
