<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace Mydex\ApiPdxSdk\Laravel\Api;


interface ReferralsApiInterface {


    /**
     * Operation getAllReferrals
     *
     * Retrieve rall referrals for a given member.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @return \Mydex\ApiPdxSdk\Laravel\Model\ReferralListResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function getAllReferrals(
            string $connectionToken,
            string $uid,
            string $conId,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\ReferralListResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;


    /**
     * Operation getSingleReferral
     *
     * Retrieve a single referral by id for a given member.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @param string $id
     * @return \Mydex\ApiPdxSdk\Laravel\Model\ReferralSingleResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function getSingleReferral(
            string $connectionToken,
            string $uid,
            string $conId,
            string $id,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\ReferralSingleResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;


    /**
     * Operation postSelfReferral
     *
     * Supports self-referral.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @param null | \Mydex\ApiPdxSdk\Laravel\Model\SelfReferralRequestBody $selfReferralRequestBody
     * @return \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse | \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function postSelfReferral(
            string $connectionToken,
            string $uid,
            string $conId,
            ?\Mydex\ApiPdxSdk\Laravel\Model\SelfReferralRequestBody $selfReferralRequestBody,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;


    /**
     * Operation updateReferralStatus
     *
     * Supports updating the status of a referral.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @param null | \Mydex\ApiPdxSdk\Laravel\Model\ReferralStatusUpdateRequestBody $referralStatusUpdateRequestBody
     * @return \Mydex\ApiPdxSdk\Laravel\Model\UpdateResponse | \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function updateReferralStatus(
            string $connectionToken,
            string $uid,
            string $conId,
            ?\Mydex\ApiPdxSdk\Laravel\Model\ReferralStatusUpdateRequestBody $referralStatusUpdateRequestBody,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\UpdateResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;

}
