<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace Mydex\ApiPdxSdk\Laravel\Api;


interface SecureMessagesApiInterface {


    /**
     * Operation getSecureMessageConversation
     *
     * Retrieve all secure messages for a given conversation.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @param string $conversationId
     * @return \Mydex\ApiPdxSdk\Laravel\Model\SecureMessageConversationResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function getSecureMessageConversation(
            string $connectionToken,
            string $uid,
            string $conId,
            string $conversationId,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\SecureMessageConversationResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;


    /**
     * Operation postSecureMessageReceive
     *
     * Supports sending a message to the member's PDS.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @param null | \Mydex\ApiPdxSdk\Laravel\Model\SecureMessageReceiveRequest $secureMessageReceiveRequest
     * @return \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse | \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function postSecureMessageReceive(
            string $connectionToken,
            string $uid,
            string $conId,
            ?\Mydex\ApiPdxSdk\Laravel\Model\SecureMessageReceiveRequest $secureMessageReceiveRequest,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;


    /**
     * Operation postSecureMessageSend
     *
     * Supports sending a message from the member's PDS.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @param null | \Mydex\ApiPdxSdk\Laravel\Model\SecureMessageSendRequest $secureMessageSendRequest
     * @return \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse | \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function postSecureMessageSend(
            string $connectionToken,
            string $uid,
            string $conId,
            ?\Mydex\ApiPdxSdk\Laravel\Model\SecureMessageSendRequest $secureMessageSendRequest,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\CreateResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\ErrorResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;

}
