<?php declare(strict_types=1);

/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace Mydex\ApiPdxSdk\Laravel\Api;


interface TimelineApiInterface {


    /**
     * Operation getTimeline
     *
     * Retrieve list of timeline items.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @return \Mydex\ApiPdxSdk\Laravel\Model\TimelineResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function getTimeline(
            string $connectionToken,
            string $uid,
            string $conId,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\TimelineResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;


    /**
     * Operation getTimelineItem
     *
     * Retrieve a single timeline item.
     * @param string $connectionToken
     * @param string $uid
     * @param string $conId
     * @param \Mydex\ApiPdxSdk\Laravel\Model\GetTimelineItemFeatureBlockParameter $featureBlock
     * @param int $featureBlockId
     * @return \Mydex\ApiPdxSdk\Laravel\Model\TimelineSingleItemResponse | \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
     */
    public function getTimelineItem(
            string $connectionToken,
            string $uid,
            string $conId,
            \Mydex\ApiPdxSdk\Laravel\Model\GetTimelineItemFeatureBlockParameter $featureBlock,
            int $featureBlockId,
    ):
        \Mydex\ApiPdxSdk\Laravel\Model\TimelineSingleItemResponse | 
        \Mydex\ApiPdxSdk\Laravel\Model\AuthErrorResponse
    ;

}
